### ISSUE TITLE
Missing passive skills

### ISSUE THREAD

**Issue by g0shu** [oMaN-Rod/palworld-save-pal#14]
Philanthropist, Fit as a Fiddle, Easygoing, Sickly and Shabby, out of the ones added in 0.3.1.0, didn't check all the old ones.
![image](https://github.com/user-attachments/assets/45f6adec-3a74-46f5-8d01-9a0d07116d56)

**Comment by oMaN-Rod** [comment]
Thanks for point these out, they've been added to the latest [release](https://github.com/oMaN-Rod/palworld-save-pal/releases/tag/v0.4.7)
