### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by Millionsofcats** [oMaN-Rod/palworld-save-pal#15]
[Level.zip](https://github.com/user-attachments/files/17269409/Level.zip)
![擷取](https://github.com/user-attachments/assets/5b63bda0-e270-4210-9bbb-488b1c7afb93)
Not sure what causes this, please help to identify the issue. zip file is attached, thank you.

**Comment by oMaN-Rod** [comment]
Your save file is missing the Players folder, watch the first video on the [User Guide](https://github.com/oMaN-Rod/palworld-save-pal/wiki/%F0%9F%8E%AE-Usage)
