### ISSUE TITLE
Error processing zip file: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by CharlyRien** [oMaN-Rod/palworld-save-pal#4]
Hello,

just tried to use for the first time this program by downloading the latest release from my windows 11 latest build and just got this error from the title of this issue.

I'm not able to drag and drop my zip file created on windows unfortunately. 

Any help would be appreciated.

**Comment by oMaN-Rod** [comment]
This issue happens with older save files, you need to load the save in Palworld v0.3.7.x first, shutdown your game or server, then use this tool.

**Comment by CharlyRien** [comment]
I'm using a save from a server running v0.3.7.58983

**Comment by oMaN-Rod** [comment]
Do you mind sharing the save file? You can share it on discord if you prefer, link is on the project home page.
