### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by Ispanikas** [oMaN-Rod/palworld-save-pal#5]
``Hello Great Sage,

I face an issue where my 168MB .zip file no longer wroks and I get infinite loading, making the file smaller (deleting the "backup") helps. No idea why, this is a new world, updated Palworld, no mods (even skins).

![image](https://github.com/user-attachments/assets/02a96a5b-604c-445e-9d94-267f1a5ca690)
![image](https://github.com/user-attachments/assets/38411def-63c7-48c4-a2ef-18552b8bab9a)
![image](https://github.com/user-attachments/assets/681038da-682d-4b64-8007-5247d2556e4b)

I can confirm my PC is high-end and shouldn't be the reason 🗡️ 🩸 

```
ToastItem.CNeWEkms.js:103 Clearing message: get_presets
ToastItem.CNeWEkms.js:103 Message cleared get_presets
ToastItem.CNeWEkms.js:103 Setting new message: {type: 'progress_message', data: 'Uploading zip file 🚀...'}
ToastItem.CNeWEkms.js:103 Clearing message: progress_message
ToastItem.CNeWEkms.js:103 Message cleared progress_message
2.hYqw3e1I.js:30 Uncaught RangeError: Invalid array length
    at Function.from (<anonymous>)
    at g.onload (2.hYqw3e1I.js:30:41452)
g.onload @ 2.hYqw3e1I.js:30
load
m @ 2.hYqw3e1I.js:30
g @ disclose-version.DoLtg718.js:1
```

**Comment by oMaN-Rod** [comment]
The save file zip is unusually large, check out the first video in the [Usage Guide](https://github.com/oMaN-Rod/palworld-save-pal/wiki/%F0%9F%8E%AE-Usage). If you are still having issues join the discord and send me your save files.
